RCB_CRUD_DJANGO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('crud.urls', namespace='crud')),
]

if settings.DEBUG:  # Serve media files only in development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'

urlpatterns = [
    path('',views.list_player, name='list_player'),
    path('create/', views.create_player, name='create_player'),
    path('view/<int:pk>/', views.view_player, name='view_player'),
    path('update/<int:pk>/', views.update_player, name='update_player'),
    path('delete/<int:pk>/', views.delete_player, name='delete_player'),
    path('super_user/', views.create_super, name="create_super"),
]

crud/models.py
from django.db import models
from cloudinary.models import CloudinaryField

class Food(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Player(models.Model):
    role_choices = [
        ("Batsman", "Batsman"),
        ("Bowler", "Bowler"),
        ("All_Rounder", "All_Rounder"),
        ("Wicket_Keeper", "Wicket_Keeper"),
    ]
    country_choices = [
        ("India", "India"),
        ("Bangladesh","Bangladesh"),
        ("Sri_Lanka","Sri_Lanka"),
        ("Australia","Australia"),
        ("NewZeland","NewZeland"),
        ("England","England"),
        ("South_Africa","South_Africa"),
        ("West_Indies", "West_Indies"),
        ("Other","Other"),
    ]

    name = models.CharField(max_length=200)
    age = models.IntegerField()
    role = models.CharField(max_length=100, choices=role_choices)
    country = models.CharField(max_length=100, choices=country_choices)
    # profile_pic = models.ImageField(upload_to="player/")
    profile_pic = CloudinaryField()
    is_captain = models.BooleanField(default=False)
    fav_food = models.ManyToManyField(Food)

    def __str__(self):
        return f"{self.name} - {self.role}"

crud/forms.py
from django import forms
from .models import Player, Food

class PlayerForm(forms.ModelForm):
    fav_food = forms.ModelMultipleChoiceField(
        queryset=Food.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Player
        fields = "__all__"
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Adding Bootstrap classes
        for field_name, field in self.fields.items():
            if field_name not in ['fav_food', 'is_captain']:
                field.widget.attrs.update({'class': 'form-control'})
        
        self.fields['name'].widget.attrs.update(
            {'placeholder': 'Enter player Name'}
        )
        self.fields['age'].widget.attrs.update(
            {'placeholder': 'Enter player Age'}
        )

        self.fields["role"].choices = list(self.fields["role"].choices)
        self.fields["role"].choices.pop(0)

        self.fields["country"].choices = list(self.fields["country"].choices)
        self.fields["country"].choices.pop(0)

        # Special handling for checkboxes (BooleanField and ManyToManyField)
        self.fields['is_captain'].widget.attrs.update({'class': 'form-check-input'})
        # self.fields['fav_food'].widget.attrs.update({'class': 'form-check-input'})

crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Player
from .forms import PlayerForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist

#Create
def create_player(request):
    try:
        if request.method == "POST":
            rec = PlayerForm(request.POST, request.FILES)
            if rec.is_valid():
                p = rec.save()
                messages.success(request, f'"{p.name}" Created successfully!!')
                return redirect("crud:list_player")
            else:
                messages.error(request, 'Invalid form data')
                print("Form Errors:", rec.errors)  # Debugging
                return render(
                    request,
                    'crud/create_player.html',
                    {"form":rec},
                )
        else:
            form = PlayerForm()
            return render(
                request,
                'crud/create_player.html',
                {"form":form},
            )
    except Exception as e:
        messages.error(request, f'Unexpected Error while creating Player: {str(e)}')
        return redirect("crud:list_player")


#Read All
def list_player(request):
    try:
        all_players = Player.objects.prefetch_related("fav_food").all()
        return render(
            request,
            'crud/list_player.html',
            { "all_players":all_players },
        )
    except Exception as e:
        messages.error(request, f'Unexpected Error while fetching players: {str(e)}')
        return redirect("crud:list_player")

#Read one
def view_player(request, pk):
    # try:
        player = get_object_or_404(Player, pk=pk)
        return render(
            request,
            "crud/view_player.html",
            {"player":player},
        )
    # except Exception as e:
    #     messages.error(request, f'Unexpected Error while fetching player: {str(e)}')
    #     return redirect("crud:list_player")

#Update
def update_player(request, pk):
    try:
        player = get_object_or_404(Player, pk=pk)
        if request.method == "POST":
            form = PlayerForm(request.POST, request.FILES, instance=player)
            if form.is_valid():
                p = form.save()
                messages.success(request, f'"{p.name}" Updated successfully!!')
                return redirect("crud:list_player")
            else:
                messages.error(request, 'Invalid form data')
                print("Form Errors:", form.errors)  # Debugging
                return render(
                    request,
                    'crud/update_player.html',
                    {"form":form},
                )
        else:
            form = PlayerForm(instance=player)
            return render(
                request,
                "crud/update_player.html",
                {"form":form},
            )
    except Exception as e:
        messages.error(request, f"Error while Updating Player: {str(e)}")
        return redirect("crud:list_player")


#Delete
def delete_player(request, pk):
    try:
        player = get_object_or_404(Player, pk=pk)
        player_name = player.name  # Store before deletion
        player.delete()
        messages.success(request, f'"{player_name}" Deleted Successfully!')
        return redirect("crud:list_player")
    except Exception as e:
        messages.error(request, f"Unexpected Error while deleting: {str(e)}")
        return redirect("crud:list_player")

#create super user
def create_super(request):
    try:
        if not User.objects.filter(username="root").exists():
            User.objects.create_superuser("root", "", "root")
            return HttpResponse("Superuser created! Username: root, Password: root")
        return HttpResponse("Superuser already exists!")
    except Exception as e:
        messages.error(request, f"Unexpected Error while Creating SuperUser: {str(e)}")
        return redirect("crud:list_player")

crud/templates/crud/create_player.html
{% extends 'base.html' %}

{% block title %}  
Create Player
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'crud/css/style_crud.css' %}">
<div class="container my-4">
    <div class="text-center">
        <h3 class="border-bottom border-2 d-inline-block">Create Player</h3>
    </div>
    <div>
        <p><span class="color_red">*</span>Mandatory fields</p>
    </div>
    <form action="" method="post" enctype="multipart/form-data" onsubmit="return validateCreate()">
        {% csrf_token %}
        
        <div class="row">
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="id_name" class="custom_label form-label">Name:<span class="color_red">*</span></label>
                    {{form.name}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="id_age" class="custom_label form-label">Age:<span class="color_red">*</span></label>
                    {{form.age}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="id_role" class="custom_label form-label">Role:<span class="color_red">*</span></label>
                    <select class="form-select" id="id_role" name="role" required>
                        <option value="" disabled selected>--Select--</option>
                        {% for val, lbl in form.role.field.choices %}
                        <option value="{{val}}">{{lbl}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="my-3">
                    <label for="id_country" class="custom_label form-label">Country:<span class="color_red">*</span></label>
                    <select name="country" id="id_country" class="form-select" required>
                        <option value="" selected disabled>--Select--</option>
                        {% for val2, lbl2 in form.country.field.choices %}
                        <option value="{{val2}}">{{lbl2}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="my-3">
                    <label for="id_profile_pic" class="custom_label form-label">Profile pic:<span class="color_red">*</span></label>
                    {{form.profile_pic}}
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-2">
                <div class="my-3">
                    <label for="id_is_captain" class="form-label custom_label">Is Captain?:</label>
                    {{form.is_captain}}
                </div>
            </div>
            
            <div class="col-md-2">
                <div class="my-3">
                    <label for="id_fav_food" class="custom_label form-label">Favourite Food:<span class="color_red">*</span></label>
                    {{form.fav_food}}
                </div>
            </div>
            
        </div>
        <div class="text-end">
            <input type="submit" class="btn custom_btn btn-success" value="Create">
        </div>

    </form>
</div>

<script>
    function validateCreate(){
        favFood = document.getElementsByName("fav_food");
        for(let i = 0;i < favFood.length; i++) {
            if(favFood[i].checked === true) {
                return true;
            }
        }
        alert("Please select atleast one Favourite Food.")
        return false;
    }
</script>
{% endblock %}

crud/templates/crud/list_player.html
{% extends 'base.html' %}

{% block title %}  
Players List
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'crud/css/style_crud.css' %}">
<div class="container my-4">
    <div class="text-center">
        <h3 class="border-bottom border-2 d-inline-block">Players List</h3>
    </div>
    <div class="text-end mb-4">
        <a href="{% url 'crud:create_player' %}" class="btn btn-success custom_btn">Create Player</a>
    </div>
    <div class="list_table_container">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Player</th>
                    <th>Role</th>
                    <th class="player_country">Country</th>
                    <th class="text-center player_action">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for player in all_players %}
                <tr>
                    <td class="wid">{{forloop.counter}}. {{player.name}}</td>
                    <td class="wid">{{player.role}}</td>
                    <td class="player_country">{{player.country}}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'crud:view_player' pk=player.pk %}" class="btn btn-info">View</a>
                            <a href="{% url 'crud:update_player' pk=player.pk %}" class="btn btn-warning">Update</a>
                            <a onclick="return confirm('Are you sure to delete: {{player.name}}')" href="{% url 'crud:delete_player' pk=player.pk %}" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
                {% empty %}
                <tr><td  class="text-center" colspan="4">No Data</td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

crud/templates/crud/update_player.html
{% extends 'base.html' %}

{% block title %}  
Update Player
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'crud/css/style_crud.css' %}">
<div class="container my-4">
    <div class="text-center">
        <h3 class="border-bottom border-2 d-inline-block">Update Player</h3>
    </div>
    <div>
        <p><span class="color_red">*</span>Mandatory fields</p>
    </div>
    <form action="" method="post" enctype="multipart/form-data" onsubmit="return validateCreate()">
        {% csrf_token %}
        
        <div class="row">
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="id_name" class="custom_label form-label">Name:<span class="color_red">*</span></label>
                    {{form.name}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="id_age" class="custom_label form-label">Age:<span class="color_red">*</span></label>
                    {{form.age}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <label for="id_role" class="custom_label form-label">Role:<span class="color_red">*</span></label>
                    <select class="form-select" id="id_role" name="role" required>
                        <option value="" disabled>--Select--</option>
                        {% for val, lbl in form.role.field.choices %}
                        <option value="{{val}}" {% if form.instance.role == val %} selected {% endif %} >{{lbl}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="my-3">
                    <label for="id_country" class="custom_label form-label">Country:<span class="color_red">*</span></label>
                    <select name="country" id="id_country" class="form-select" required>
                        <option value="" disabled>--Select--</option>
                        {% for val2, lbl2 in form.country.field.choices %}
                        <option value="{{val2}}" {% if form.instance.country == val2 %}selected{% endif %}>{{lbl2}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="my-3">
                    <label for="id_profile_pic" class="custom_label form-label">Profile pic:<span class="color_red">*</span></label>
                    {{form.profile_pic}}
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-2">
                <div class="my-3">
                    <label for="id_is_captain" class="form-label custom_label">Is Captain?:</label>
                    {{form.is_captain}}
                </div>
            </div>
            
            <div class="col-md-2">
                <div class="my-3">
                    <label for="id_fav_food" class="custom_label form-label">Favourite Food:<span class="color_red">*</span></label>
                    {{form.fav_food}}
                </div>
            </div>
            
        </div>
        <div class="text-end">
            <input type="submit" class="btn custom_btn btn-success" value="Update">
        </div>

    </form>
</div>

<script>
    function validateCreate(){
        favFood = document.getElementsByName("fav_food");
        for(let i = 0;i < favFood.length; i++) {
            if(favFood[i].checked === true) {
                return true;
            }
        }
        alert("Please select atleast one Favourite Food.")
        return false;
    }
</script>
{% endblock %}

crud/templates/crud/view_player.html
{% extends 'base.html' %}

{% block title %}  
Player Details
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'crud/css/style_crud.css' %}">
<div class="container my-4">
    <div class="text-center">
        <h3 class="border-bottom border-2 d-inline-block">Player Details</h3>
    </div>
    <div class="text-end mb-4">
        <a href="{% url 'crud:list_player' %}" class="btn btn-success custom_btn">Goto Home</a>
    </div>
    <div class="player_details_div rounded">
        <div class="row">
            <div class="col-md-3">
                <div class="profile_pic_div">
                    {% if player.profile_pic %}
                    <img class="profile_pic rounded" src="{{player.profile_pic.url}}" alt="{{player.name}}"></li>
                    {% else %}
                    No Image
                    {% endif %}
                </div>
            </div>
            <div class="col-md-9 p-3">
                <ul>
                    <li><span class="fields_style">Name:</span> {{player.name}}</li>
                    <li><span class="fields_style">Age:</span> {{player.age}}</li>
                    <li><span class="fields_style">Role:</span> {{player.role}}</li>
                    <li><span class="fields_style">Country:</span> {{player.country}}</li>
                    <li><span class="fields_style">Is Captain?:</span> 
                        {% if player.is_captain == True %} Yes {% else %} No {% endif %}
                    </li>
                    <li><span class="fields_style">Fav Food:</span> {% for fd in player.fav_food.all %}{{fd.name}}{% if not forloop.last %},{% endif %}  {% endfor %}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}